### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MareoRaft**
It seems to be working nicely in iTerm2 for me.

I would be happy to run your testing suite or manually test a list of features if you'd like, but if so, let me know what needs to be done.

Have a great day,
Matt

### CODE REVIEW

**Comment by feluxe** [comment]
@MareoRaft Thanks for your PR, I just noticed it too late... I'm not very used to getting PRs on my personal projects ;-)...  In the mean time the repo changed a lot...

Testing sty is quite simple, just clone the repo, `cd` into it and run `python3 -m tests`. Then see if the output matches what you see on the screen. :-)

**Comment by MareoRaft** [comment]
blink not blinking

hidden not hidden

strike not stricken

rs_ things not working

6, 10-21, 26-27, 30, 37-40 all display white question marks

The default color scheme may display colors in a very light pastel way.  But this is fixable by changing the color scheme in preferences.

**Comment by MareoRaft** [comment]
I'm not sure if all of that information should be listed in known issues.  But there you have it.  Everything I didn't mention appears to be working nicely.

**Comment by MareoRaft** [comment]
Also, `Yakuake` was previously listed as supported (in the old version), but in your new docs, it is not listed.

Now that I've given you all the information, it should be easy for you to make the updates yourself; however, if you would prefer for me to go ahead and open a new PR, I would be happy to, just let me know.

**Comment by feluxe** [comment]
@MareoRaft thanks for the update!

I'm happy to add the things you mention to the list.

> rs_ things not working

Does this mean none of the following sequences work with iTerm2?
* `rs.all`
* `rs.fg`
* `rs.bg`
* `rs.i`

> Also, Yakuake was previously listed as supported (in the old version), but in your new docs, it is not listed.

The new list only includes terminals that have issues with the common ANSI sequences sty uses. There are no issues reported for Yakuake so far.

**Comment by MareoRaft** [comment]
> Does this mean none of the following sequences work with iTerm2?

All of the `rs` things do not produce color.  If the purpose of `rs` is to reset the style back to the default for the terminal, then it is working.

> The new list only includes terminals that have issues with the common ANSI sequences sty uses. 

Since your page is titled "Terminal Support", I would expect a list of supported terminals.  I would suggest maintaing a growing list of all terminals supported, or alternatively putting a note at the top that says that any terminal not listed is in fact supported.

P.S.  Sorry for delay.  I've been so busy with work.

**Comment by feluxe** [comment]
Thanks for the update!

>  If the purpose of rs is to reset the style back to the default for the terminal, then it is working.

Yes, `rs` is for resetting. That's nice to hear! I'll update the `iTerm2` entry.

> Since your page is titled "Terminal Support", I would expect a list of supported terminals.

That makes sense, I'll rename the section to "Known Issues", then it's clear. :-)

**Comment by MareoRaft** [comment]
thanks!

**Pull request closed without merging**
